name: Deploy Streamlit app

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from, e.g., 'master'

jobs:
  build:
    runs-on: windows-2022  # Use Windows Server 2022 runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.7.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.7.9  # Use 3.7.9 or another version of Python 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Deploy Streamlit app
      run: |
        streamlit run app.py  # Replace with your app's entry script
