name: Deploy Streamlit app

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the deployment

jobs:
  build:
    runs-on: windows-2022  # Change to a Windows runner (Windows Server 2022)

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.7.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.7.11  # Ensure you're using Python 3.7.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Deploy Streamlit app
      run: |
        streamlit run your_app.py  # Replace `your_app.py` with your actual app script
