name: Deploy Streamlit app

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from, e.g., 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.7.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.11  # Ensure you're using Python 3.7.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Deploy to Streamlit
      run: |
        streamlit run your_app.py  # Replace `your_app.py` with your app's entry script
