name: Deploy Streamlit app

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from, e.g., 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.7.11 manually
      run: |
        sudo apt-get update
        sudo apt-get install python3.7
        python3.7 -m ensurepip --upgrade
        python3.7 -m pip install --upgrade pip
      shell: bash

    - name: Install dependencies
      run: |
        python3.7 -m pip install -r requirements.txt  # Use python3.7 explicitly

    - name: Deploy Streamlit app
      run: |
        streamlit run app.py  # Replace 'app.py' with your actual app script
